### ISSUE TITLE
Increase dump_logs time granularity to microseconds

### ISSUE THREAD

**Issue by abereziny** [nspcc-dev/neofs-testlib#33]
Currently some tests can be executed for less than 1 second. 
And we analyze logs for each test so sometimes logs can have entries from previous test

According to https://www.freedesktop.org/software/systemd/man/systemd.time.html# and https://docs.docker.com/engine/reference/commandline/logs/ it can be done if we add `.%f` to the time format here:
https://github.com/nspcc-dev/neofs-testlib-plugin-sbercloud/blob/master/src/neofs_testlib_plugin_sbercloud/sbercloud_host.py#L137,L138

**Comment by evgeniiz321** [comment]
not relevant with the latest testcases version
