### ISSUE TITLE
Incorrect parsing of response in the test.

### ISSUE THREAD

**Issue by tatiana-nspcc** [nspcc-dev/neofs-testlib#83]
When I run the test "Test Put over HTTP/Curl, Get over HTTP/Curl for large object" or "Test Put/Get over HTTP using Curl utility," it incorrectly parses the response. This one is OK:
```
REQUEST: 'http://http.neofs.devenv/upload/8RCBdQbqkvA8Ua83DBZY8ra5JTXrzcx5BDFXjtn8wme'
RESPONSE:
 {'object_id': 'irY8nYGk4ibL3rWnEykK27esGo3zsvZhxCUMMMW5xeT', 'container_id': '8RCBdQbqkvA8Ua83DBZY8ra5JTXrzcx5BDFXjtn8wme'}
```
## Current Behavior

This response is marked as wrong:
```
{"container_id":"41cxpZjt9C7r1MpV3PBmnfurRP7xFEkAhhp8NjCy5UQc","object_id":"3kKzfjWtRRoYkPEh9nXNV8eB3gVVttKLZYgxefrWKbgt"}
```
I've got a message:
```
File "/home/tanya/neo/projects/nspcc-dev/neofs-testcases/venv.local-pytest/lib/python3.10/site-packages/allure_commons/_allure.py", line 192, in impl
    return func(*a, **kw)
  File "/home/tanya/neo/projects/nspcc-dev/neofs-testcases/robot/resources/lib/python_keywords/http_gate.py", line 245, in upload_via_http_gate_curl
    raise AssertionError(f'Could not find "object_id" in {output}')
```
## Expected Behavior

An extra space or an absent space shouldn't cause the test to fail.
## Possible Solution

Perhaps it would be better to properly parse the JSON response here.:
https://github.com/nspcc-dev/neofs-testcases/blob/ef04906beaba71ca8d6e633b01601456f0582f47/robot/resources/lib/python_keywords/http_gate.py#L243 

## Context

I encountered this issue while testing the rest-gw.

**Comment by roman-khimov** [comment]
JSON is JSON and must be treated accordingly.

**Comment by MaxGelbakhiani** [comment]
The problem was caused by the output format. output might contain something like:

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n100  575k    0     0    0  575k      0  2884k --:--:-- --:--:-- --:--:-- 2879k\n100 1537k    0     0    0 1537k      0  1258k --:--:--  0:00:01 --:--:-- 1258k{\n\t"object_id": "CUf93a2T6NocdLud77CtZcbsEfgQNMHBjfKjXQ3zKSe1",\n\t"container_id": "kLJKURtdNXpGc31qVhMmyD4zsjcY2nMTVXdbDBC3CHw"\n}\n\n100 1537k  100   129    0 1537k     75   895k  0:00:01  0:00:01 --:--:--  895k\n
```

So I've added options to extract JSON out of it, including multiline cases, which I believe caused @tatiana-nspcc 's issue. And added JSON parsing as well
